export interface IssueResult {
  title: string;
  category: string;
  description: string | null;
  proposedChange?: string | null;
  votes: number;
}

function formatDate(d: Date): string {
  return d.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
}

export function generatePetitionMarkdown(
  cycleStart: Date,
  cycleEnd: Date,
  issues: IssueResult[]
): string {
  const lines: string[] = [];

  lines.push("# Helldivers 2 Community Petition");
  lines.push("");
  lines.push(`*Voting period: ${formatDate(cycleStart)} \u2013 ${formatDate(cycleEnd)}*`);
  lines.push("");
  lines.push(
    "This petition represents the collective voice of the Helldivers 2 community. " +
    "Each issue listed below was submitted, reviewed, and approved by community moderators before being put to a vote. " +
    "The results reflect genuine player sentiment and are presented here to inform the development team at Arrowhead Game Studios."
  );
  lines.push("");
  lines.push("## Top Issues");
  lines.push("");

  issues.forEach((issue, index) => {
    lines.push(`### ${index + 1}. ${issue.title}`);
    lines.push("");
    lines.push(`**Category:** ${issue.category}`);
    lines.push("");
    lines.push(`**Votes:** ${issue.votes}`);
    lines.push("");
    if (issue.description) {
      lines.push(`**Problem Statement:** ${issue.description}`);
      lines.push("");
    }
    if (issue.proposedChange) {
      lines.push(`**Proposed Change:** ${issue.proposedChange}`);
    } else {
      lines.push(`**Proposed Change:** *No specific change proposed — community amendment invited.*`);
    }
    lines.push("");
  });

  lines.push("---");
  lines.push("");
  lines.push(
    "*Generated by HD2 Council \u2014 community-driven, not affiliated with Arrowhead Game Studios.*"
  );

  return lines.join("\n");
}
