import type { AgendaItem, Motion } from "@nr-yn/db";
import { selectIssues, type SelectionConfig } from "@nr-yn/governance";

export { selectIssues, type SelectionConfig, type SelectedIssue } from "@nr-yn/governance";

export function generatePetitionDraft(
  cycleTitle: string,
  agendaItems: (AgendaItem & { motions: Motion[] })[],
  config: SelectionConfig
): string {
  const issues = selectIssues(agendaItems, config);

  const lines: string[] = [
    "# Helldivers 2 Community Petition",
    "",
    `*${cycleTitle}*`,
    "",
    "This petition represents the collective voice of the Helldivers 2 community. " +
    "Each issue was submitted, reviewed, and approved by community moderators before " +
    "being put to a vote. Results reflect genuine player sentiment.",
    "",
    "## Top Issues",
    "",
  ];

  for (const [i, issue] of issues.entries()) {
    lines.push(`### ${i + 1}. ${issue.title}`);
    lines.push("");
    lines.push(`**Category:** ${issue.category}  **Votes:** ${issue.votes}`);
    lines.push("");
    if (issue.description) {
      lines.push(`**Problem Statement:** ${issue.description}`);
      lines.push("");
    }
    lines.push(
      `**Proposed Change:** ${issue.proposedChange ?? "*No specific change proposed — community amendment invited.*"}`
    );
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push("*Generated by HD2 Council — community-driven, not affiliated with Arrowhead Game Studios.*");

  return lines.join("\n");
}
