import type { AgendaItem, Motion } from "@platform/db";

interface SelectionConfig {
  topN: number;
  minVotes: number;
  categoryCaps: Record<string, number>;
  categoryGuarantees: Record<string, number>;
}

interface SelectedIssue {
  title: string;
  category: string;
  description: string | null;
  proposedChange: string | null;
  votes: number;
}

export function selectIssues(
  agendaItems: (AgendaItem & { motions: Motion[] })[],
  config: SelectionConfig
): SelectedIssue[] {
  const { topN, minVotes, categoryCaps, categoryGuarantees } = config;

  const allApproved = agendaItems
    .map((a) => {
      const motion = a.motions.find((m) => m.outcome === "passed" && m.motionType !== "amendment");
      if (!motion) return null;
      const notes = (() => {
        try { return JSON.parse(motion.specialNotes ?? "{}") as { proposedChange?: string }; }
        catch { return {}; }
      })();
      return {
        title: a.title,
        category: motion.resolutionType ?? "qol",
        description: a.description,
        proposedChange: notes.proposedChange ?? null,
        votes: motion.votesFor ?? 0,
      };
    })
    .filter((x): x is NonNullable<typeof x> => x !== null);

  const qualified = allApproved.filter((i) => i.votes >= minVotes);

  const byCategory: Record<string, typeof qualified> = {};
  for (const issue of qualified) {
    (byCategory[issue.category] ??= []).push(issue);
  }
  for (const cat of Object.keys(byCategory)) {
    byCategory[cat].sort((a, b) => b.votes - a.votes);
  }

  const selected: typeof qualified = [];
  const selectedCount: Record<string, number> = {};

  for (const [cat, guarantee] of Object.entries(categoryGuarantees)) {
    if (guarantee > 0) {
      const candidates = byCategory[cat] ?? [];
      for (let i = 0; i < guarantee && i < candidates.length; i++) {
        selected.push(candidates[i]);
        selectedCount[cat] = (selectedCount[cat] ?? 0) + 1;
      }
    }
  }

  const globalRanked = [...qualified].sort((a, b) => b.votes - a.votes);
  for (const issue of globalRanked) {
    if (selected.length >= topN) break;
    if (selected.includes(issue)) continue;
    const catCount = selectedCount[issue.category] ?? 0;
    const cap = categoryCaps[issue.category] ?? topN;
    if (catCount < cap) {
      selected.push(issue);
      selectedCount[issue.category] = catCount + 1;
    }
  }

  return selected.sort((a, b) => b.votes - a.votes);
}

export function generatePetitionDraft(
  cycleTitle: string,
  agendaItems: (AgendaItem & { motions: Motion[] })[],
  config: SelectionConfig
): string {
  const issues = selectIssues(agendaItems, config);

  const lines: string[] = [
    "# Helldivers 2 Community Petition",
    "",
    `*${cycleTitle}*`,
    "",
    "This petition represents the collective voice of the Helldivers 2 community. " +
    "Each issue was submitted, reviewed, and approved by community moderators before " +
    "being put to a vote. Results reflect genuine player sentiment.",
    "",
    "## Top Issues",
    "",
  ];

  for (const [i, issue] of issues.entries()) {
    lines.push(`### ${i + 1}. ${issue.title}`);
    lines.push("");
    lines.push(`**Category:** ${issue.category}  **Votes:** ${issue.votes}`);
    lines.push("");
    if (issue.description) {
      lines.push(`**Problem Statement:** ${issue.description}`);
      lines.push("");
    }
    lines.push(
      `**Proposed Change:** ${issue.proposedChange ?? "*No specific change proposed — community amendment invited.*"}`
    );
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push("*Generated by HD2 Council — community-driven, not affiliated with Arrowhead Game Studios.*");

  return lines.join("\n");
}
